url: "https://bananbashar.github.io"
baseurl: "/agency-jekyll-theme"

# Site settings
title: "Banan Bashar"
email: "bbaljarrah20@ph.just.edu.jo"
description: "Clinical Pharmacist | Data Analyst | Researcher. Passionate about transforming clinical data into meaningful insights to support evidence-based decisions."


  
# Social networks usernames 
social:
  - title: github
    url: https://github.com/bananbashar
  - title: linkedin
    url: https://linkedin.com/in/bananbashar
  - title: email
    url: bbaljarrah20@ph.just.edu.jo
# Postal address 
address:
  - line: Amman, Jordan
  - line: Available for remote research collaboration

# Build settings
markdown: kramdown
permalink: pretty